name: Create Pull Request
on:
  push:
    branches: 
      - "dev"
jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create pull request from dev to main
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUBACTIONS }}
          title: Merge dev into main
          base: main
          branch: dev
          author: dclong <dclong@users.noreply.github.com>
          assignees: dclong