name: Create Pull Request
on:
  push:
    branches: 
      - "dev"
jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    container:
      image: dclong/rust-cicd
    steps:
      - uses: actions/checkout@v3
      - name: Create PR from dev to main
        run: |
          .github/workflows/pr.py --token ${{ secrets.GITHUBACTIONS }}
